shape: sequence_diagram
auth; client; server

auth.shape: cloud
client.shape: person

client."Main menu"

JWT: {
  auth -> client: logged
  Play: {
    client.t -> server.t: ws connect
    server.t -> server.t: uuid from jwt
    server.t -> client.t: packet/connectionSuccess
  }
  client -> auth: |gql { logout } |
}

client."Connection success"

client -> server: packet/listCharacters
server -> client: packet/listCharactersResponse

creating: {
  client -> server: packet/createCharacter
  server -> client: packet/listCharactersResponse
}

selecting: {
  client -> server: packet/selectCharacter
  server -> client: packet/joinGame
  client -> client: load state game
}

client -> server: packet/joinGameReady